version: '3'
services:
  sql:
    image: mysql:latest
    container_name: sql
    restart: always
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: MySQLPassword@123
       MYSQL_DATABASE: company
    volumes:
      - ./data/mysql:/var/lib/mysql